### ISSUE TITLE
keyPrefix issue no data passed, Error: Missing lock for job  (v5)

### ISSUE THREAD

**Issue by jericopulvera** [Rocketseat/adonis-bull#116]
**Description of bug**
keyPrefix breaks the Queue process

**To Reproduce**

1. Create Fresh Adonis v5 
2. Install Adonis Bull for v5 using Adonis server runtime
3. Add any keyPrefix value e.g keyPrefix: 'c1'
4. Reload the Adonis server.
5. Add something to the Queue.
6. Check the bullboard.

**Expected behavior**

The job receives data and is processed successfully.

**Exception or Error**

<pre><code>
Error: Missing lock for job 1. failed
    at Scripts.finishedErrors (/Users/jericopulvera/Code/hello-world/node_modules/bullmq/src/classes/scripts.ts:341:16)
    at Job.moveToFailed (/Users/jericopulvera/Code/hello-world/node_modules/bullmq/src/classes/job.ts:523:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handleFailed (/Users/jericopulvera/Code/hello-world/node_modules/bullmq/src/classes/worker.ts:581:9)
    at Worker.retryIfFailed (/Users/jericopulvera/Code/hello-world/node_modules/bullmq/src/classes/worker.ts:725:16)
    at Worker.run (/Users/jericopulvera/Code/hello-world/node_modules/bullmq/src/classes/worker.ts:351:34)
</code></pre>

**Screenshots**

With keyPrefix
<img width="721" alt="image" src="https://user-images.githubusercontent.com/23246308/169270005-6046fb31-0e74-4b14-ac7e-fb04ece55c32.png">

Without keyPrefix
<img width="758" alt="image" src="https://user-images.githubusercontent.com/23246308/169270195-d808539d-2230-46ee-b9a7-15ea24f06f6b.png">

**Comment by jericopulvera** [comment]
The fix would be to use a prefix key in WorkerOptions and QueueOptions.

Unfortunately, the QueueOptions is not typed and you'll have to ignore it.

```ts
import { JobContract, QueueOptions, WorkerOptions } from "@ioc:Rocketseat/Bull";
import Env from "@ioc:Adonis/Core/Env";

const prefix = Env.get("BULL_PREFIX");

export default class UserRegisterEmail implements JobContract {
  public key = "UserRegisterEmail";

  public queueOptions: QueueOptions = {
    // @ts-ignore
    prefix,
  };

  public workerOptions: WorkerOptions = {
    prefix,
  };

  public async handle(job) {
    console.log(job.data, this.key);

    return job.data;
  }
}
```

Issue details can be found in the BullMQ repo.
https://github.com/taskforcesh/bullmq/issues/424
