### ISSUE TITLE
v5 job file malformed

### ISSUE THREAD

**Issue by Venipa** [Rocketseat/adonis-bull#122]
**Description of bug**
Unable to start adonis with bullmq, "Invalid or unexpected token"

**To Reproduce**

1. Create jobs
2. listen for queue
3. after a few days (for me) it threw that error

![image](https://user-images.githubusercontent.com/17952364/197540605-d81a547f-45bb-46cb-8228-d81f22d97bee.png)

**Expected behavior**

job.js not getting malformed

**Exception or Error**

<pre><code>
{"type":"SyntaxError","message":"Invalid or unexpected token","stack":"/var/www/maplefiles/node_modules/bullmq/dist/cjs/classes/job.js:1\n\n\n\nSyntaxError: Invalid or unexpected token\n    at Object.compileFunction (node:vm:360:18)\n    at wrapSafe (node:internal/modules/cjs/loader:1055:15)\n    at Module._compile (node:internal/modules/cjs/loader:1090:27)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Module.require (node:internal/modules/cjs/loader:1028:19)\n    at Module.Hook._require.Module.require (/usr/local/share/.config/yarn/global/node_modules/require-in-the-middle/index.js:101:39)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/www/maplefiles/node_modules/bullmq/src/classes/queue-base.ts:5:1)
</code></pre>

**Screenshots**

![image](https://user-images.githubusercontent.com/17952364/197540605-d81a547f-45bb-46cb-8228-d81f22d97bee.png)

**Environment:**

 - OS: Debian 11
 - Node v16.17.1
 - Adonis 5.8.0

**Comment by Venipa** [comment]
could it be that `Job.discard()` is causing this?
