### ISSUE TITLE
Adonis 4: Installation fails

### ISSUE THREAD

**Issue by dspangenberg** [Rocketseat/adonis-bull#87]
Installation with `adonis install @rocketseat/adonis-bull` fails

**To Reproduce**

Type adonis install @rocketseat/adonis-bull in terminal.

**Expected behavior**

Installation of the the librrary

**Exception or Error**

Command failed: npm i --save @rocketseat/adonis-bull@legacy
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @rocketseat/adonis-bull@legacy.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Screenshots**

![image](https://user-images.githubusercontent.com/166466/119504296-20d6d580-bd6c-11eb-84a7-9550dfc5e218.png)

**Environment:**

OS: macOS 11.3.1
Node: v12.22.1
Adonis: 4.1.0

**Additional context**

LOG-File:
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   '@rocketseat/adonis-bull@legacy'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose npm-session 2750695b08ab55c7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@rocketseat%2fadonis-bull 795ms (from cache)
8 silly registry:manifest no matching version for @rocketseat/adonis-bull@legacy in the cache. Forcing revalidation.
9 http fetch GET 200 https://registry.npmjs.org/@rocketseat%2fadonis-bull 197ms
10 silly fetchPackageMetaData error for @rocketseat/adonis-bull@legacy No matching version found for @rocketseat/adonis-bull@legacy.
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 2075ms
13 verbose type tag
14 verbose stack @rocketseat/adonis-bull: No matching version found for @rocketseat/adonis-bull@legacy.
14 verbose stack     at pickManifest (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
14 verbose stack     at /Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18
14 verbose stack     at tryCatcher (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
14 verbose stack     at Promise._settlePromise (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
14 verbose stack     at Promise._settlePromise0 (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
14 verbose stack     at Promise._settlePromises (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
14 verbose stack     at _drainQueueStep (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
14 verbose stack     at _drainQueue (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
14 verbose stack     at Async._drainQueues (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/dspangenberg/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
14 verbose stack     at processImmediate (internal/timers.js:461:21)
15 verbose cwd /Users/dspangenberg/Projects/tourismusnetz.com/japi
16 verbose Darwin 20.4.0
17 verbose argv "/Users/dspangenberg/.nvm/versions/node/v12.22.1/bin/node" "/Users/dspangenberg/.nvm/versions/node/v12.22.1/bin/npm" "i" "--save" "@rocketseat/adonis-bull@legacy"
18 verbose node v12.22.1
19 verbose npm  v6.14.12
20 error code ETARGET
21 error notarget No matching version found for @rocketseat/adonis-bull@legacy.
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]

**Comment by RodolfoSilva** [comment]
@dspangenberg Use the `v0.2.5` version, the latest version is't compatible with adonis 4

**Comment by dspangenberg** [comment]
Hi @RodolfoSilva,

I've followed the instructions on https://github.com/Rocketseat/adonis-bull, which are obviously for Adonis 4 (This documentation refers to the stable version of Adonis Bull, for Adonis v4.x)

`adonis install @rocketseat/adonis-bull

After the error, I tried it with` yarn add @rocketseat/adonis-bull`, and successfully, 0.3.0 was installed.

There were some problems until I've removed '@rocketseat/adonis-bull/providers/Command' from AceProviders in start/app.js.

Best regards,
Danny

**Comment by wemersonrv** [comment]
Hello.

The last version with support for Adonis v4 is the **v0.2.5**? There are plans to update this version or will just update versions with Adonis V5 support?
