### ISSUE TITLE
Cannot read property 'bull' of undefined

### ISSUE THREAD

**Issue by koteesy** [Rocketseat/adonis-bull#93]
Hello, i follow all steps on https://github.com/Rocketseat/adonis-bull/tree/alpha

But when i try dipatch job i got error:

```
Cannot read property 'bull' of undefined
    err: {
      "type": "TypeError",
      "message": "Cannot read property 'bull' of undefined",
      "stack":
          TypeError: Cannot read property 'bull' of undefined
              at BullManager.add (/var/www/myapp/node_modules/@rocketseat/adonis-bull/build/src/BullManager.js:75:34)
              at TrackingController.add (/var/www/myapp/app/Controllers/Http/TrackingController.ts:12:10)
              at Injector.callAsync (/var/www/myapp/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
              at processTicksAndRejections (internal/process/task_queues.js:93:5)
      "status": 500
    }
```

Also, when i try call ```node ace bull:listen``` process output:
```
{ board: undefined }
[1628705465006] INFO (myapp/2046 on MacBook-Air-Igor.local): Queue processing started
```

And immediately shutdown.

package.json
```
"@adonisjs/core": "^5.1.11",
"@rocketseat/adonis-bull": "^1.0.4",
```

**Comment by koteesy** [comment]
Alright, i found which exactly thrown error, if we have empty jobs array in ``start/jobs`, that throws all errors which i specified in issue.
